"""Guided end-to-end assessment wizard for TRACER-CV.

This is a step-through demonstration aid. It does NOT replace the
full Assessments workspace or duplicate any engine logic. Assessment
execution is delegated to AssessmentManager / assessment_runner.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from PySide6.QtCore import Qt, Signal
from PySide6.QtWidgets import (
    QFileDialog, QFrame, QGridLayout, QHBoxLayout, QLabel, QLineEdit,
    QMessageBox, QProgressBar, QPushButton, QScrollArea, QSizePolicy,
    QSplitter, QTextEdit, QVBoxLayout, QWidget,
)

from desktop.widgets.components import SectionCard, SeverityBadge, StatusCard


# ---------------------------------------------------------------------------
# Step definitions
# ---------------------------------------------------------------------------

STEPS = [
    (1,  "Select Dataset",        "Select the local dataset directory to assess."),
    (2,  "Select Model",          "Select the local model file to assess (optional)."),
    (3,  "Configure Assessment",  "Review and confirm the assessment configuration."),
    (4,  "Run Assessment",        "Execute the assessment engines."),
    (5,  "Review Findings",       "Review the findings generated by the assessment."),
    (6,  "Review Evidence",       "Review the supporting evidence."),
    (7,  "Verify Provenance",     "Verify the inference provenance chain."),
    (8,  "Review Audit",          "Review the tamper-evident audit trail."),
    (9,  "Generate Report",       "Generate and export the assurance report."),
]


# ---------------------------------------------------------------------------
# Step indicator widget
# ---------------------------------------------------------------------------

class StepIndicator(QFrame):
    """Vertical list of numbered steps with active/done/pending states."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setFixedWidth(200)
        self.setObjectName("scopePanel")
        layout = QVBoxLayout(self)
        layout.setContentsMargins(10, 14, 10, 14)
        layout.setSpacing(4)
        header = QLabel("ASSESSMENT STEPS")
        header.setObjectName("metricLabel")
        layout.addWidget(header)
        self._step_frames: dict[int, QFrame] = {}
        for num, name, _ in STEPS:
            frame = QFrame()
            frame.setObjectName("stepCard")
            frame.setProperty("state", "pending")
            frame.setMinimumHeight(44)
            row = QHBoxLayout(frame)
            row.setContentsMargins(8, 6, 8, 6)
            num_label = QLabel(str(num))
            num_label.setFixedWidth(20)
            num_label.setAlignment(Qt.AlignCenter)
            num_label.setStyleSheet("font-weight:700; font-size:9pt;")
            name_label = QLabel(name)
            name_label.setWordWrap(True)
            row.addWidget(num_label)
            row.addWidget(name_label, 1)
            layout.addWidget(frame)
            self._step_frames[num] = frame
        layout.addStretch()

    def set_state(self, step: int, state: str) -> None:
        """state: 'pending' | 'active' | 'done'"""
        frame = self._step_frames.get(step)
        if frame:
            frame.setProperty("state", state)
            frame.style().unpolish(frame)
            frame.style().polish(frame)
            frame.update()


# ---------------------------------------------------------------------------
# Individual step pages
# ---------------------------------------------------------------------------

class _StepPage(QWidget):
    def __init__(self, num: int, name: str, description: str, parent=None):
        super().__init__(parent)
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(12)
        header = QLabel(f"Step {num}: {name}")
        header.setObjectName("pageTitle")
        layout.addWidget(header)
        desc = QLabel(description)
        desc.setWordWrap(True)
        desc.setObjectName("mutedText")
        layout.addWidget(desc)
        self.body = QVBoxLayout()
        layout.addLayout(self.body)
        layout.addStretch()
        self._layout = layout


class SelectDatasetPage(_StepPage):
    def __init__(self, state: dict, parent=None):
        super().__init__(1, "Select Dataset",
                         "Select the local dataset directory to assess.", parent)
        self._state = state
        row = QHBoxLayout()
        self._path_edit = QLineEdit()
        self._path_edit.setPlaceholderText("Path to dataset directory…")
        self._path_edit.textChanged.connect(lambda t: state.update({"dataset_path": t}))
        if state.get("dataset_path"):
            self._path_edit.setText(str(state["dataset_path"]))
        browse = QPushButton("Browse…")
        browse.clicked.connect(self._browse)
        row.addWidget(self._path_edit, 1)
        row.addWidget(browse)
        self.body.addLayout(row)
        self._status = QLabel("")
        self._status.setWordWrap(True)
        self.body.addWidget(self._status)
        note = QLabel(
            "The dataset directory will be assessed using the configured A1–A8 engines. "
            "Only local directories are accepted."
        )
        note.setWordWrap(True)
        note.setObjectName("mutedText")
        self.body.addWidget(note)

    def _browse(self):
        path = QFileDialog.getExistingDirectory(self, "Select dataset directory")
        if path:
            self._path_edit.setText(path)
            self._state["dataset_path"] = path

    def validate(self) -> bool:
        path = self._path_edit.text().strip()
        if not path:
            self._status.setText("Please select a dataset directory.")
            return False
        p = Path(path)
        if not p.is_dir():
            self._status.setText(f"Directory not found: {path}")
            return False
        self._status.setText("")
        self._state["dataset_path"] = path
        return True


class SelectModelPage(_StepPage):
    def __init__(self, state: dict, parent=None):
        super().__init__(2, "Select Model",
                         "Select the local model file to assess (optional — skip to assess dataset only).",
                         parent)
        self._state = state
        row = QHBoxLayout()
        self._path_edit = QLineEdit()
        self._path_edit.setPlaceholderText("Path to model file (optional)…")
        self._path_edit.textChanged.connect(lambda t: state.update({"model_path": t or None}))
        if state.get("model_path"):
            self._path_edit.setText(str(state["model_path"]))
        browse = QPushButton("Browse…")
        browse.clicked.connect(self._browse)
        row.addWidget(self._path_edit, 1)
        row.addWidget(browse)
        self.body.addLayout(row)
        self._status = QLabel("")
        self._status.setWordWrap(True)
        self.body.addWidget(self._status)
        note = QLabel(
            "Supported formats: .pt / .pth (TorchScript), .onnx (conditional). "
            "Model files are not executed during registration; B1 hashes bytes only. "
            "B2/B3/B4 require a compatible callable adapter. Leave blank to skip."
        )
        note.setWordWrap(True)
        note.setObjectName("mutedText")
        self.body.addWidget(note)

    def _browse(self):
        path, _ = QFileDialog.getOpenFileName(
            self, "Select model file", "",
            "Model files (*.pt *.pth *.onnx *.bin *.weights);;All files (*)",
        )
        if path:
            self._path_edit.setText(path)
            self._state["model_path"] = path

    def validate(self) -> bool:
        path = self._path_edit.text().strip()
        if path:
            p = Path(path)
            if not p.is_file():
                self._status.setText(f"File not found: {path}")
                return False
            self._state["model_path"] = path
        else:
            self._state["model_path"] = None
        self._status.setText("")
        return True


class ConfigurePage(_StepPage):
    def __init__(self, state: dict, config: Any, parent=None):
        super().__init__(3, "Configure Assessment",
                         "Review the configuration and name this assessment.", parent)
        self._state = state
        name_row = QHBoxLayout()
        name_row.addWidget(QLabel("Assessment name:"))
        self._name_edit = QLineEdit()
        self._name_edit.setPlaceholderText("Optional descriptive name…")
        self._name_edit.textChanged.connect(lambda t: state.update({"name": t}))
        if state.get("name"):
            self._name_edit.setText(state["name"])
        name_row.addWidget(self._name_edit, 1)
        self.body.addLayout(name_row)

        summary = SectionCard("Configuration Summary")
        dataset_path = state.get("dataset_path") or "— not set —"
        model_path = state.get("model_path") or "— not selected (dataset only) —"
        offline = getattr(config, "offline_mode", True)
        engines = "A1–A8 (dataset integrity)"
        if state.get("model_path"):
            engines += " · B1–B4 (model integrity)"
        engines += " · C1–C5 (provenance, shift, findings, audit, report)"
        for label, value in (
            ("Dataset", str(dataset_path)),
            ("Model", str(model_path)),
            ("Offline mode", "Enabled" if offline else "Disabled"),
            ("Engines", engines),
        ):
            row = QLabel(f"<b>{label}:</b>  {value}")
            row.setWordWrap(True)
            summary.content.addWidget(row)
        self.body.addWidget(summary)

        warning = QLabel(
            "Assessment engines will run locally and may take several minutes "
            "depending on dataset size and available compute. "
            "No network access will be performed."
        )
        warning.setWordWrap(True)
        warning.setObjectName("mutedText")
        self.body.addWidget(warning)

    def validate(self) -> bool:
        return True  # Name is optional


class RunAssessmentPage(_StepPage):
    assessment_completed = Signal(dict)  # emits assessment result

    def __init__(self, state: dict, services: dict, config: Any, parent=None):
        super().__init__(4, "Run Assessment", "Execute the assessment engines.", parent)
        self._state = state
        self._services = services
        self._config = config
        self._running = False

        self._start_button = QPushButton("Start Assessment")
        self._start_button.setObjectName("primary")
        self._start_button.clicked.connect(self._run)
        self.body.addWidget(self._start_button)

        self._progress = QProgressBar()
        self._progress.setRange(0, 0)  # indeterminate
        self._progress.setVisible(False)
        self.body.addWidget(self._progress)

        self._log = QTextEdit()
        self._log.setReadOnly(True)
        self._log.setMaximumHeight(180)
        self._log.setPlaceholderText("Assessment log will appear here…")
        self.body.addWidget(self._log)

        self._status_label = QLabel("")
        self._status_label.setWordWrap(True)
        self.body.addWidget(self._status_label)

    def _log_msg(self, msg: str) -> None:
        self._log.append(msg)

    def _run(self) -> None:
        if self._running:
            return
        dataset_path = self._state.get("dataset_path")
        if not dataset_path or not Path(dataset_path).is_dir():
            QMessageBox.warning(self, "Missing dataset",
                                "Please go back and select a valid dataset directory.")
            return

        manager = (self._services.get("assessment_manager")
                   if self._services else None)
        if manager is None:
            self._status_label.setText(
                "Assessment services are not available. "
                "Please restart the application and try again."
            )
            return

        self._running = True
        self._start_button.setEnabled(False)
        self._progress.setVisible(True)
        self._log_msg("Starting assessment…")

        name = self._state.get("name") or "Guided assessment"
        model_path = self._state.get("model_path")

        try:
            from backend.core.assessment import Assessment
            from pathlib import Path as _Path
            kwargs: dict[str, Any] = {
                "name": name,
                "dataset_path": str(dataset_path),
            }
            if model_path:
                kwargs["model_path"] = str(model_path)
            record = manager.create(**kwargs)
            self._log_msg(f"Assessment created: {record.get('assessment_id', '—')}")
            self._log_msg("Running engines…")
            result = manager.run(record["assessment_id"],
                                 on_event=lambda eng, msg, _: self._log_msg(f"[{eng}] {msg}"))
            self._state["assessment_result"] = result
            self._state["assessment_id"] = record.get("assessment_id", "")
            self._log_msg("Assessment completed.")
            self._status_label.setText(
                f"✓ Assessment {record.get('assessment_id', '')} completed."
            )
            self.assessment_completed.emit(result or {})
        except Exception as exc:
            self._log_msg(f"Error: {exc}")
            self._status_label.setText(f"Assessment failed: {exc}")
        finally:
            self._running = False
            self._progress.setVisible(False)
            self._start_button.setEnabled(True)

    def validate(self) -> bool:
        return bool(self._state.get("assessment_result") is not None
                    or self._state.get("assessment_id"))


class _SummaryStep(_StepPage):
    """Steps 5–8: summary card + navigate button."""

    def __init__(self, num: int, name: str, description: str,
                 nav_label: str, nav_key: str,
                 state: dict, parent=None):
        super().__init__(num, name, description, parent)
        self._state = state
        self._nav_key = nav_key
        self._summary_card = SectionCard(f"{name} Summary")
        self._summary_card.content.addWidget(QLabel("Load assessment results to see summary."))
        self.body.addWidget(self._summary_card)
        nav_button = QPushButton(f"Go to {nav_label}")
        nav_button.clicked.connect(lambda: self._navigate())
        self.body.addWidget(nav_button)
        self._nav_fn = None  # set by wizard

    def _navigate(self):
        if self._nav_fn:
            self._nav_fn(self._nav_key)

    def refresh(self, result: dict) -> None:
        """Update the summary card from assessment result."""
        while self._summary_card.content.count() > 1:
            item = self._summary_card.content.takeAt(1)
            if item.widget():
                item.widget().deleteLater()
        for key, label in self._summary_fields():
            value = result.get(key)
            if value is not None:
                lbl = QLabel(f"<b>{label}:</b>  {value}")
                lbl.setWordWrap(True)
                self._summary_card.content.addWidget(lbl)

    def _summary_fields(self) -> list[tuple[str, str]]:
        return []

    def validate(self) -> bool:
        return True


class ReviewFindingsPage(_SummaryStep):
    def __init__(self, state: dict, parent=None):
        super().__init__(5, "Review Findings",
                         "Review the findings generated by the assessment.",
                         "Findings Workspace", "FINDINGS", state, parent)

    def _summary_fields(self):
        return [("finding_count", "Findings"), ("highest_observed_severity", "Highest severity")]

    def refresh(self, result: dict) -> None:
        findings_block = result.get("findings_and_evidence", {})
        findings = findings_block.get("findings", []) if isinstance(findings_block, dict) else []
        counts: dict[str, int] = {}
        for f in findings if isinstance(findings, list) else []:
            sev = str(f.get("severity", "none")).lower()
            counts[sev] = counts.get(sev, 0) + 1
        while self._summary_card.content.count() > 1:
            item = self._summary_card.content.takeAt(1)
            if item.widget():
                item.widget().deleteLater()
        total = len(findings) if isinstance(findings, list) else 0
        self._summary_card.content.addWidget(QLabel(f"<b>Total findings:</b>  {total}"))
        for sev, count in sorted(counts.items()):
            badge = SeverityBadge(f"{sev.upper()}: {count}", sev)
            self._summary_card.content.addWidget(badge)
        if not findings:
            self._summary_card.content.addWidget(
                QLabel("No findings were recorded in the current assessment.")
            )


class ReportPage(_StepPage):
    def __init__(self, state: dict, parent=None):
        super().__init__(9, "Generate Report",
                         "Generate and export the assurance report.", parent)
        self._state = state
        self._nav_fn = None

        report_card = SectionCard("Report")
        report_card.content.addWidget(
            QLabel("The assurance report summarises all assessment evidence.")
        )
        self.body.addWidget(report_card)

        row = QHBoxLayout()
        view_btn = QPushButton("View Report")
        view_btn.clicked.connect(lambda: self._nav_fn("REPORTS") if self._nav_fn else None)
        export_btn = QPushButton("Export PDF")
        export_btn.setObjectName("primary")
        export_btn.clicked.connect(self._export_pdf)
        row.addWidget(view_btn)
        row.addWidget(export_btn)
        row.addStretch()
        self.body.addLayout(row)

        self._status = QLabel("")
        self._status.setWordWrap(True)
        self.body.addWidget(self._status)

        done_note = QLabel(
            "Assessment complete. Use the sidebar to navigate to any workspace for "
            "detailed analysis. The findings, evidence, audit trail and report "
            "remain available for analyst review."
        )
        done_note.setWordWrap(True)
        done_note.setObjectName("mutedText")
        self.body.addWidget(done_note)

    def _export_pdf(self):
        from PySide6.QtWidgets import QFileDialog
        assessment_id = self._state.get("assessment_id", "")
        default_name = f"TRACER-CV-{assessment_id}-report.pdf" if assessment_id else "tracer_cv_report.pdf"
        path, _ = QFileDialog.getSaveFileName(self, "Export Assurance Report PDF",
                                              default_name, "PDF (*.pdf)")
        if not path:
            return
        try:
            from desktop.reporting import write_assurance_pdf
            from pathlib import Path
            import json
            result_data = self._state.get("assessment_result") or {}
            report = result_data if result_data else {}
            # Try to load from filesystem if available
            if assessment_id:
                from backend.core.local_config import LocalConfig
                config = LocalConfig.load()
                report_path = (config.reports_dir / "assessments" / assessment_id
                               / "tracer_cv_assurance_report.json").resolve()
                if report_path.is_file():
                    report = json.loads(report_path.read_text(encoding="utf-8"))
            assessment = {
                "assessment_id": assessment_id,
                "status": "completed",
            }
            out = write_assurance_pdf(report, assessment, Path(path))
            self._status.setText(
                f"PDF exported: {Path(out['path']).name}\n"
                f"SHA-256: {out['sha256'][:32]}…"
            )
        except Exception as exc:
            self._status.setText(f"Export failed: {exc}")

    def validate(self) -> bool:
        return True


# ---------------------------------------------------------------------------
# Main wizard
# ---------------------------------------------------------------------------

class GuidedAssessmentWizard(QWidget):
    """Nine-step guided assessment wizard.

    Emits navigate_to(str) for the main app to route to a workspace page.
    Does not duplicate engine logic; delegates execution to AssessmentManager.
    """
    navigate_to = Signal(str)

    def __init__(self, services: dict | None = None,
                 config: Any = None, parent=None):
        super().__init__(parent)
        self._services = services or {}
        self._config = config
        self._state: dict[str, Any] = {}
        self._current_step = 1
        self.step_count = len(STEPS)

        outer = QHBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0)
        outer.setSpacing(0)

        self._indicator = StepIndicator()
        outer.addWidget(self._indicator)

        right = QVBoxLayout()
        right.setContentsMargins(24, 20, 24, 16)
        right.setSpacing(12)

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QFrame.NoFrame)
        self._content_widget = QWidget()
        self._content_layout = QVBoxLayout(self._content_widget)
        self._content_layout.setContentsMargins(0, 0, 0, 0)
        scroll.setWidget(self._content_widget)
        right.addWidget(scroll, 1)

        # Navigation buttons
        btn_row = QHBoxLayout()
        self._back_button = QPushButton("← Back")
        self._back_button.clicked.connect(self._go_back)
        self._next_button = QPushButton("Next →")
        self._next_button.setObjectName("primary")
        self._next_button.clicked.connect(self._go_next)
        self._done_button = QPushButton("Done")
        self._done_button.setObjectName("success")
        self._done_button.setVisible(False)
        self._done_button.clicked.connect(lambda: self.navigate_to.emit("MISSION CONTROL"))
        btn_row.addWidget(self._back_button)
        btn_row.addStretch()
        btn_row.addWidget(self._done_button)
        btn_row.addWidget(self._next_button)
        right.addLayout(btn_row)

        outer.addLayout(right, 1)

        # Build step pages
        self._pages: dict[int, QWidget] = {}
        self._build_pages()
        self._show_step(1)

    def _build_pages(self) -> None:
        self._pages[1] = SelectDatasetPage(self._state)
        self._pages[2] = SelectModelPage(self._state)
        self._pages[3] = ConfigurePage(self._state, self._config)
        run_page = RunAssessmentPage(self._state, self._services, self._config)
        run_page.assessment_completed.connect(self._on_assessment_done)
        self._pages[4] = run_page
        self._pages[5] = ReviewFindingsPage(self._state)
        self._pages[6] = _SummaryStep(6, "Review Evidence", "Review the supporting evidence.",
                                       "Evidence Explorer", "EVIDENCE", self._state)
        self._pages[7] = _SummaryStep(7, "Verify Provenance", "Verify the provenance chain.",
                                       "Provenance Workspace", "Inference Provenance", self._state)
        self._pages[8] = _SummaryStep(8, "Review Audit", "Review the audit trail.",
                                       "Audit Trail", "AUDIT TRAIL", self._state)
        self._pages[9] = ReportPage(self._state)

        # Wire navigate_to signal through the summary pages
        for step in (6, 7, 8):
            page = self._pages[step]
            if hasattr(page, "_nav_fn"):
                page._nav_fn = lambda k: self.navigate_to.emit(k)
        if hasattr(self._pages[9], "_nav_fn"):
            self._pages[9]._nav_fn = lambda k: self.navigate_to.emit(k)
        if hasattr(self._pages[5], "_nav_fn"):
            self._pages[5]._nav_fn = lambda k: self.navigate_to.emit(k)

    def _on_assessment_done(self, result: dict) -> None:
        self._state["assessment_result"] = result
        # Refresh summary pages if they exist
        for step in (5,):
            page = self._pages.get(step)
            if page and hasattr(page, "refresh"):
                page.refresh(result.get("executive_summary") or result)
        # Auto-advance
        self._go_next()

    def _show_step(self, step: int) -> None:
        # Clear content
        while self._content_layout.count():
            item = self._content_layout.takeAt(0)
            if item.widget():
                item.widget().setParent(None)

        # Update indicator
        for s in range(1, self.step_count + 1):
            if s < step:
                self._indicator.set_state(s, "done")
            elif s == step:
                self._indicator.set_state(s, "active")
            else:
                self._indicator.set_state(s, "pending")

        page = self._pages.get(step)
        if page:
            self._content_layout.addWidget(page)
            page.show()

        self._current_step = step
        self._back_button.setEnabled(step > 1)
        is_last = (step == self.step_count)
        self._next_button.setVisible(not is_last)
        self._done_button.setVisible(is_last)

    def _go_next(self) -> None:
        page = self._pages.get(self._current_step)
        if page and hasattr(page, "validate") and not page.validate():
            return
        next_step = self._current_step + 1
        if next_step <= self.step_count:
            self._show_step(next_step)

    def _go_back(self) -> None:
        prev_step = self._current_step - 1
        if prev_step >= 1:
            self._show_step(prev_step)
